AppBundle\Entity\Prices:
    type: entity
    table: prices
    uniqueConstraints:
        i:
            columns:
                - price_type_id
                - goods_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        priceTypeId:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: price_type_id
        goodsId:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: goods_id
        price:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
    lifecycleCallbacks: {  }
